In [1]:
!pip install pandas numpy

Requirement already satisfied: pandas in c:\users\st\appdata\local\programs\python\python310\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\st\appdata\local\programs\python\python310\lib\site-packages (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\st\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\st\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\st\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\st\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: C:\Users\ST\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [8]:
# 1. Pehla table banaya (Roll No aur City)
data1 = {
    'roll_no': [1, 2, 3, 4],
    'city': ['Lahore', 'Karachi', 'Islamabad', 'Peshawar']
}
df1 = pd.DataFrame(data1)

# 2. Dosra table banaya (Roll No aur Marks)
# Note: Is mein hum ne jan booch kar roll_no 5 dala hai aur 4 ko chor diya hai taakay joins samajh sakein
data2 = {
    'roll_no': [1, 2, 3, 5],
    'marks': [85, 77, 78, 92]
}
df2 = pd.DataFrame(data2)

# Dono tables ko screen par dekhne ke liye
print("--- Table 1 (df1) ---")
print(df1)
print("\n--- Table 2 (df2) ---")
print(df2)

--- Table 1 (df1) ---
   roll_no       city
0        1     Lahore
1        2    Karachi
2        3  Islamabad
3        4   Peshawar

--- Table 2 (df2) ---
   roll_no  marks
0        1     85
1        2     77
2        3     78
3        5     92

In [9]:
# 'on=roll_no' ka matlab hai roll number ki bunyad par joro
# 'how=inner' ka matlab hai sirf common data uthao
inner_join_df = pd.merge(df1, df2, on='roll_no', how='inner')

# Result dekhne ke liye
inner_join_df

   roll_no       city  marks
0        1     Lahore     85
1        2    Karachi     77
2        3  Islamabad     78

In [10]:
# 'how=left' ka matlab hai pehle table (df1) ko pora rakho
left_join_df = pd.merge(df1, df2, on='roll_no', how='left')

# Result dekhne ke liye
left_join_df

   roll_no       city  marks
0        1     Lahore   85.0
1        2    Karachi   77.0
2        3  Islamabad   78.0
3        4   Peshawar    NaN

In [11]:
# 'how=right' ka matlab hai dosray table (df2) ko poora rakho
right_join_df = pd.merge(df1, df2, on='roll_no', how='right')

# Result dekhne ke liye
right_join_df

   roll_no       city  marks
0        1     Lahore     85
1        2    Karachi     77
2        3  Islamabad     78
3        5        NaN     92

In [12]:
# 'how=outer' ka matlab hai dono tables ka poora data ikotha kar do
outer_join_df = pd.merge(df1, df2, on='roll_no', how='outer')

# Result dekhne ke liye
outer_join_df

   roll_no       city  marks
0        1     Lahore   85.0
1        2    Karachi   77.0
2        3  Islamabad   78.0
3        4   Peshawar    NaN
4        5        NaN   92.0

In [13]:
# Hum Pandas ko bol rahay hain ke 'outer_join_df' mein se sirf wo row uthao jahan city 'Lahore' hai
lahore_df = outer_join_df[outer_join_df['city'] == 'Lahore']

# Result dekhne ke liye
lahore_df

   roll_no    city  marks
0        1  Lahore   85.0

In [14]:
# Hum Pandas ko bol rahay hain ke 'outer_join_df' mein se sirf wo row uthao jahan city 'Lahore' hai
Pershawar_df = outer_join_df[outer_join_df['city'] == 'Peshawar']

# Result dekhne ke liye
Pershawar_df

   roll_no      city  marks
3        4  Peshawar    NaN

In [15]:
# Hum Pandas ko bol rahay hain ke 'outer_join_df' mein se sirf wo rows uthao jahan city ya to Lahore ho ya Peshawar
lahore_peshawar_df = outer_join_df[outer_join_df['city'].isin(['Lahore', 'Peshawar'])]

# Result dekhne ke liye
lahore_peshawar_df

   roll_no      city  marks
0        1    Lahore   85.0
3        4  Peshawar    NaN