In [1]:
import pandas as pd


pak_weather = pd.DataFrame({
    "city": ["Lahore", "Karachi"],
    "temperature": [32, 35],
    "humidity": [80, 75]
})


pak_weather_2 = pd.DataFrame({
    "city": ["Mianwali", "Multan"],
    "temperature": [40, 42],
    "humidity": [60, 55]
})

print("df1:\n", pak_weather)
print("\ndf2:\n", pak_weather_2)

df1:
       city  temperature  humidity
0   Lahore           32        80
1  Karachi           35        75

df2:
        city  temperature  humidity
0  Mianwali           40        60
1    Multan           42        55

In [2]:
final_weather_clean = pd.concat([pak_weather, pak_weather_2], ignore_index=True)
final_weather_clean

       city  temperature  humidity
0    Lahore           32        80
1   Karachi           35        75
2  Mianwali           40        60
3    Multan           42        55

In [3]:
weather_with_labels = pd.concat([pak_weather, pak_weather_2], keys=["pak_jan", "pak_feb"])

weather_with_labels

               city  temperature  humidity
pak_jan 0    Lahore           32        80
        1   Karachi           35        75
pak_feb 0  Mianwali           40        60
        1    Multan           42        55